#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# What a session is given at its start: the rules that hold, for the shells
# they hold for, and nothing for a shell the project does not use.

set -f
payload="$(cat)"

rules="$(dirname "$0")/../rules"
[ -d "$rules" ] || exit 0

. "$(dirname "$0")/lib/readable-shell-lib.sh"
. "$(dirname "$0")/lib/say.sh"
. "$(dirname "$0")/lib/state.sh"

apply_migrations

event="$(hook_event_of "$payload")"
project="$(hook_field "$payload" cwd)"
settings_from_project "$project"

# The shells whose files are held. With no project named there is nothing to
# detect from, so every known shell is printed rather than none.
files_shells=""
if scope_holds files; then
  files_shells="$(shells_chosen)"
  if [ "$files_shells" = "detect" ]; then
    if [ -n "$project" ] && [ -d "$project" ]; then
      files_shells="$(project_shells "$project" | tr '\n' ' ' | sed 's/ $//')"
    else
      files_shells="$known_shells"
    fi
  fi
fi

commands_held=""
scope_holds commands && commands_held=1

# A command an agent runs is Bourne shell whatever the project holds.
printed_shells="$files_shells"
if [ -n "$commands_held" ]; then
  case " $printed_shells " in
    *" bourne "*) ;;
    *) printed_shells="$printed_shells bourne" ;;
  esac
fi

if [ -n "$files_shells" ] && [ -n "$commands_held" ]; then
  held_to="It applies to shell written into a file and to a one-off command alike."
elif [ -n "$files_shells" ]; then
  held_to="It applies to shell written into a file; a one-off command is not held to it."
elif [ -n "$commands_held" ]; then
  held_to="It applies to a one-off command you run; shell written into a file is not held to it."
else
  exit 0
fi

printed() {
  local shell first=1
  if rule_holds options; then
    sed "s|{held-to}|$held_to|" "$rules/options.md"
    first=""
  fi
  if rule_holds names; then
    for shell in $printed_shells; do
      [ -f "$rules/names-$shell.md" ] || continue
      [ -n "$first" ] || printf '\n'
      sed "s|{held-to}|$held_to|" "$rules/names-$shell.md"
      first=""
    done
  fi
  # How a shell file is laid out is about files alone: a one-off command has no
  # functions or constants to name.
  if [ -n "$files_shells" ]; then
    for layout in functions constants early-exits; do
      layout="$rules/files-$layout.md"
      [ -f "$layout" ] || continue
      [ -n "$first" ] || printf '\n'
      cat "$layout"
      first=""
    done
  fi
}

if [ -n "$event" ]; then
  printed | hook_say "$event"
else
  printed
fi
