#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# Runs once per version, before anything reads state. 0.1.0 is the first
# version, so there is nothing yet to move.
:
