#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# The plugin these libraries were built for. Nothing else here names it.

PLUGIN_NAME='readable-shell'
PLUGIN_PREFIX='READABLE_SHELL'
PLUGIN_DISPLAY_NAME='readable-shell'

plugin_setting_default() {
  case "$1" in
    STOP_NOTE_DIRECTORY) printf '%s' '{state}/notes' ;;
    UPDATE_CHECK) printf '%s' 'on' ;;
    UPDATE_CHECK_DAYS) printf '%s' '1' ;;
    VERSION_SOURCE) printf '%s' 'https://raw.githubusercontent.com/justinkek/readable-shell/main/package.json' ;;
    RULES) printf '%s' 'names options functions constants early-exits' ;;
    SCOPE) printf '%s' 'files' ;;
    SHELLS) printf '%s' 'bourne' ;;
    ABBREVIATIONS) printf '%s' 'acc arg attr cfg cmd ctx curr desc dir dst enc fp idx len msg num opt pos prev req res src str tmp val var' ;;
    ABBREVIATIONS_ADDED) printf '%s' '' ;;
    ABBREVIATIONS_ALLOWED) printf '%s' '' ;;
    COMMANDS_QUIET) printf '%s' '[ [[ test set read export local declare readonly typeset unset shift return exit printf echo cd pwd trap wait eval exec source command type hash ulimit umask alias getopts let awk basename cat chmod chown comm cp cut date df diff dirname du env file find head hostname id kill ln ls mkdir mktemp mv nohup od paste ps python python3 rm rmdir scp sed sleep ssh stat tail tee tmux touch tr uname uniq wc which xargs' ;;
    COMMANDS_QUIET_ADDED) printf '%s' '' ;;
  esac
}

plugin_setting_kind() {
  case "$1" in
    STOP_NOTE_DIRECTORY) printf '%s' 'text' ;;
    UPDATE_CHECK) printf '%s' 'switch' ;;
    UPDATE_CHECK_DAYS) printf '%s' 'count' ;;
    VERSION_SOURCE) printf '%s' 'text' ;;
    RULES) printf '%s' 'text' ;;
    SCOPE) printf '%s' 'choice' ;;
    SHELLS) printf '%s' 'text' ;;
    ABBREVIATIONS) printf '%s' 'text' ;;
    ABBREVIATIONS_ADDED) printf '%s' 'text' ;;
    ABBREVIATIONS_ALLOWED) printf '%s' 'text' ;;
    COMMANDS_QUIET) printf '%s' 'text' ;;
    COMMANDS_QUIET_ADDED) printf '%s' 'text' ;;
  esac
}

plugin_setting_values() {
  case "$1" in
    SCOPE) printf '%s' 'both files commands' ;;
  esac
}

plugin_hook_on() {
  case "$1" in
    'guard-shell-readability.sh') printf '%s\n' 'bash' 'write' 'edit' 'multi_edit' ;;
  esac
}

plugin_session_start_hooks() {
  :
}
